### ISSUE TITLE
press key not working

### ISSUE THREAD

**Issue by kurt-rhee** [ollipal/sshkeyboard#1]
On ZorinOS which is based on Ubuntu 20.04
python 3.8
sshkeyboard 2.3.1

```
import sshkeyboard

if __name__ == '__main__':

    def press(key):
        print(key)

    sshkeyboard.listen_keyboard(
        on_press=press
    )
```

```
Traceback (most recent call last):
  File "/home/skrhee/miniconda3/envs/rc_registration/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3dded786045f>", line 1, in <module>
    runfile('/media/H/Python/Nevados/rc-registration/keystrokes/commands_v3.py', wdir='/media/H/Python/Nevados/rc-registration/keystrokes')
  File "/snap/pycharm-community/256/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-community/256/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/H/Python/Nevados/rc-registration/keystrokes/commands_v3.py", line 17, in <module>
    sshkeyboard.listen_keyboard(
  File "/home/skrhee/miniconda3/envs/rc_registration/lib/python3.8/site-packages/sshkeyboard/__init__.py", line 235, in listen_keyboard
    asyncio.run(coro)
  File "/home/skrhee/miniconda3/envs/rc_registration/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/skrhee/miniconda3/envs/rc_registration/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/skrhee/miniconda3/envs/rc_registration/lib/python3.8/site-packages/sshkeyboard/__init__.py", line 343, in listen_keyboard_manual
    with _raw(sys.stdin), _nonblocking(sys.stdin):
  File "/home/skrhee/miniconda3/envs/rc_registration/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/skrhee/miniconda3/envs/rc_registration/lib/python3.8/site-packages/sshkeyboard/__init__.py", line 455, in _raw
    original_stty = termios.tcgetattr(stream)
termios.error: (25, 'Inappropriate ioctl for device')
```

**Comment by ollipal** [comment]
Hey! Thanks for the report. I tested the code on Ubuntu 18.04 machine with Python 3.8 and I could not reproduce the error. I think it is not OS related based on my googling.

Where did you run the command? Some environments such as IDEs seem to have issues as they have not implemented proper input interfaces ([here for example](https://github.com/magmax/python-readchar/issues/11)). It seems that you are using PyCharm, could you try running `commands_v3.py` directly from the terminal?

**Comment by kurt-rhee** [comment]
Hello @ollipal thank you so much for your response.  I have stopped working on this project and a teammate of mine is working on implementing in another language.   I will close this issue request.

**Comment by Drewsername** [comment]
Encountered the same issue on ubuntu 20 with python 3.8, running in terminal produces same result. @ollipal
